version: '3.9'

services:
  traefik:
    image: traefik:v3.1
    restart: always
    container_name: traefik
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./dynamic.yml:/dynamic.yml:ro
      - ./certs:/certs
    environment:
      - LETSENCRYPT_EMAIL=ops@example.com
      - DNS_PROVIDER=cloudflare
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.blog.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.ai-blog.app`) || HostRegexp(`blog\.[a-z0-9-]+\.[a-z]{2,}`)'
      - 'traefik.http.routers.blog.entrypoints=https'
      - 'traefik.http.routers.blog.tls.certresolver=le-http'
      - 'traefik.http.routers.blog.middlewares=secure-headers,redirect-https'
      - 'traefik.http.services.blog.loadbalancer.server.url=https://topiqo.com'
    networks:
      - traefik-net
networks:
  traefik-net:
    driver: bridge
