entryPoints:
  http:
    address: ':80'
  https:
    address: ':443'

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /dynamic.yml
    watch: true

certificatesResolvers:
  le-http:
    acme:
      email: ${LETSENCRYPT_EMAIL}
      storage: /certs/acme.json
      httpChallenge:
        entryPoint: http
log:
  level: DEBUG
  filePath: /var/log/traefik.log
  format: json
api:
  dashboard: true
  insecure: true # test only
